### PR TITLE
fix overlap in compact view

### PR DESCRIPTION
**Pull request by cycsd**
overlap

This pull request wants to fix the nodes that overlap each other in the compact view.

I think this is one solution to this problem.

fixed

if there is any side effect and bugs I didn't consider, you could let me know and I'll try to fix it.

Or if you already have a better solution for that or it is against any conventions or patterns you're using, I could alter or close it.

Thank you to make this awesome PKM tool😃.

### CODE REVIEW

**Comment by zsviczian** [comment]
Thank you, I will try this now

**Comment by zsviczian** [comment]
@cycsd,

I am looking at some of the pages with the new compact view. I'd like to ask for a bit of further help from you to improve the look. The child and parent notes seem to be organized in a haphazard way. For a clean look, I'd like them to follow a pattern. I am ok with the screenshot in your note above, that looks organized, but the screenshot below does not.

image

**Comment by zsviczian** [comment]
For now, I rolled back these changes from master.
I added you as a collaborator to this repository.
You can now open a branch in this repository and create a pull request that way. The benefit of this will be that I will also be able to commit to the branch/PR before merging to master.

please address the above issue and resubmit the PR.

Thank you!

**Comment by CarlB01** [comment]
@cycsd, I hope you find this comment! 
I would very much like to work together with you to make a better compact view! 
I did see your comments in the Layout.ts and it seems you were on track of it. Myself I am an autodidact and not a coder per se. But I have been tweaking a lot in the scene.ts parts (just never dared to make a horrid 'PR' (- come again??)  and that is where I am at the moment. I have just learnt how to make a pull request on GitHub and imagine my surprise when both you, and Zsolt have been racing to enter new code the last days at the same time I was starting to add PR/code in this otherwise 'dead' part of the universe until recently. haha. ok, If you read this - I look forward to hearing from you. I hope I can be helpful and stay out of your code at the same time. 

I have created a new fork for now. Will try to add small, safe bits in small increments. 
Regards. Carl B.

**Comment by zsviczian** [comment]
Hi @CarlB01, thanks for creating the fork. For @cycsd  here's the [link](https://github.com/zsviczian/excalibrain/tree/Compact-view---Scene-rendering) for reference.

**Comment by cycsd** [comment]
I think I know what happens in the view, it's because the align Center logic is wrong, and the residue space shouldn't be divided by node counts,
but it seems there has been a lot of change in the repository, I will check when I go back home.
very sorry for that.

**Pull request merged**
